[package]
name = "jit"
version = "0.1.0"
edition = "2021"

[dependencies]
birl = { git = "https://github.com/lazpeng/birlscript" }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm11-0"] }
thiserror = "1"
